version: "3.9"

services:
  app:
    build: .
    working_dir: /opt
    restart: always
    # environment:
    #   PGDATA: /var/lib/postgresql/data/pgdata
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: pgpassword
    #   POSTGRES_DATABASE: postgres
    volumes:
      - ./mysite:/opt
    ports:
      - 8000:8000
    depends_on:
      - db
    # tty: true
    # command: bash
    entrypoint: ["./entrypoint.sh"]

  db:
    image: postgres:15.1-bullseye
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DATABASE: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg_data:
